export const SIGN_IN_WITH_EMAIL = "auth/SIGN_IN_WITH_EMAIL";
export const SIGN_IN_WITH_EMAIL_SUCCESS = "auth/SIGN_IN_WITH_EMAIL_SUCCESS";
export const SIGN_IN_WITH_EMAIL_ERROR = "auth/SIGN_IN_WITH_EMAIL_ERROR";
export const STORE_PHONE_NUMBER = "auth/STORE_PHONE_NUMBER";

export const SIGN_UP_WITH_EMAIL = "auth/SIGN_UP_WITH_EMAIL";
export const SIGN_UP_WITH_EMAIL_SUCCESS = "auth/SIGN_UP_WITH_EMAIL_SUCCESS";
export const SIGN_UP_WITH_EMAIL_ERROR = "auth/SIGN_UP_WITH_EMAIL_ERROR";

export const SIGN_UP_PROCESSS_NAVIGATE = "auth/SIGN_UP_PROCESSS_NAVIGATE";
export const SIGN_UP_PROCESSS_NAVIGATE_SUCCESS =
  "auth/SIGN_UP_PROCESSS_NAVIGATE_SUCCESS";

export const SIGN_UP_PROCESSS_DATA = "auth/SIGN_UP_PROCESSS_DATA";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const HOME_STACK_NAVIGATE = "auth/HOME_STACK_NAVIGATE";

export const UPDATE_USER = "auth/UPDATE_USER";

export const LOG_OUT = "auth/LOG_OUT";
